server:
  port: 9050
  servlet:
    context-path: /
spring:
  application:   #\u5B9A\u4E49\u670D\u52A1\u540D\u79F0
    name: springcloud-zuul
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7000/eureka,http://localhost:7001/eureka,http://localhost:7002/eureka
  instance:
    instance-id: springcloud-zuul-9050             #\u5B9A\u4E49\u5FAE\u670D\u52A1\u7684\u540D\u79F0
    prefer-ip-address: true                        #\u662F\u5426\u663E\u793AIP\u548C\u7AEF\u53E3
