server:
    port: 8020
    servlet:
        context-path: /
eureka:
    client:
        register-with-eureka: false    #不会将自己的信息注册到eureka中
        service-url:
            #链接注册中心集群
            defaultZone: http://localhost:7000/eureka