server:
  port: 7000                      #定义注册中心端口
eureka:
  server:
    enable-self-preservation: true  #设定自我保护模式 默认值为true 不建议关闭
  instance:
    hostname: localhost        #eureka服务的实例名称
  #        lease-renewal-interval-in-seconds: 10   # 每隔10s发送一次心跳
  #        lease-expiration-duration-in-seconds: 30     # 告知服务端30秒还未收到心跳的话，就将该服务移除列表
  client:
    register-with-eureka: false   #表示注册中心 不会注册自己本身
    fetch-registry: false         #表示自己就是注册中心,不需要检索服务
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
    healthcheck:
      enabled: true